### ISSUE TITLE
Classic Era / Hardcore, amount of quests box is misalligned

### ISSUE THREAD

**Issue by Machanu** [MrEliasen/wide-quest-log-addon#1]
The box with e.g. "Quests: 10/20" is trailing off the side of the quest log window (screen resolution is 1920x1080 if that makes a difference). I'm aware you are not the original creator of the addon (and I praise you for even fixing this at all), so I'm only wondering if it would be possible to release a fix of this? Love it otherwise.

**Comment by MrEliasen** [comment]
This has been fixed, a new version is released on curse 👍🏻
